# Generated by Django 4.1.4 on 2022-12-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_littlelemonuser_qwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='littlelemonuser',
            name='qwe',
        ),
    ]
