# Generated by Django 4.1.4 on 2022-12-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='stock',
        ),
    ]
